# Generated by Django 4.1.4 on 2023-01-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sample_model',
            new_name='School',
        ),
    ]
